#cloud-config
packages:
  - docker.io
  - docker-compose

runcmd:
  - systemctl enable docker
  - systemctl start docker

  # Wait for Docker
  - |
    while ! docker info >/dev/null 2>&1; do
      echo "Docker not ready yet... retrying in 15s"
      sleep 15
    done

  # Prepare config only (no certs yet)
  - mkdir -p /opt/nginx/conf.d
  - |
    cat > /opt/nginx/conf.d/default.conf <<'EOF'
    events {}
    http {
      server {
        listen 80;
        server_name _;
        location / {
          return 200 "Nginx waiting for SSL certs...\n";
        }
      }
    }
    EOF
