#cloud-config
packages:
  - docker.io
  - docker-compose

write_files:
  - path: /opt/app/docker-compose.yml
    permissions: '0644'
    content: |
      version: '3'
      services:
        nginx:
          image: nginx:latest
          container_name: nginx-test
          ports:
            - "80:80"
            - "443:443"

runcmd:
  - systemctl enable docker
  - systemctl start docker
  - sleep 10
  - docker compose -f /opt/app/docker-compose.yml up -d
