#cloud-config
packages:
  - docker.io
  - docker-compose
  - certbot

runcmd:
  - systemctl enable docker
  - systemctl start docker
  - |
    while ! docker info >/dev/null 2>&1; do
      echo "Docker not ready yet... retrying in 15s"
      sleep 15
    done
    certbot certonly --standalone --non-interactive --agree-tos \
      -m {{EMAIL}} \
      -d {{FQDN}}
    docker run -d --name nginx-test \
      -p 80:80 -p 443:443 \
      -v /etc/letsencrypt/live/{{FQDN}}:/etc/nginx/certs:ro \
      nginx:alpine \
      sh -c "cat > /etc/nginx/conf.d/default.conf <<'EOC'
      server {
        listen 80;
        server_name {{FQDN}};
        return 301 https://\$host\$request_uri;
      }
      server {
        listen 443 ssl;
        server_name {{FQDN}};
        ssl_certificate /etc/nginx/certs/fullchain.pem;
        ssl_certificate_key /etc/nginx/certs/privkey.pem;
        location / {
          return 200 'Hello from HTTPS on {{FQDN}}!\n';
        }
      }
      EOC
      && nginx -g 'daemon off;'"

    # Renewal hook: restart nginx-test after cert renew
    mkdir -p /etc/letsencrypt/renewal-hooks/deploy
    cat > /etc/letsencrypt/renewal-hooks/deploy/restart-nginx.sh <<'HOOK'
    #!/bin/bash
    docker restart nginx-test
    HOOK
    chmod +x /etc/letsencrypt/renewal-hooks/deploy/restart-nginx.sh
