#cloud-config
packages:
  - docker.io
  - docker-compose
  - certbot

runcmd:
  - systemctl enable docker
  - systemctl start docker
  - |
    while ! docker info >/dev/null 2>&1; do
      echo "Docker not ready yet... retrying in 15s"
      sleep 15
    done
    certbot certonly --standalone --non-interactive --agree-tos \
      -m {{EMAIL}} \
      -d {{FQDN}}
    docker run -d --name nginx-test \
      -p 80:80 -p 443:443 \
      -v /etc/letsencrypt/live/{{FQDN}}:/etc/nginx/certs:ro \
      nginx:alpine
